[theme]
base = "light"
primaryColor = "#2563EB"              # balanced blue accent
backgroundColor = "#FAFAFA"           # off-white canvas
secondaryBackgroundColor = "#F0F2F5"  # subtle gray for side panels
textColor = "#111827"                 # rich black text
font = "sans serif"
